### ISSUE TITLE
error

### ISSUE THREAD

**Issue by perfect-network** [lanpangzhi/novel-api#3]
when i execute:
```
npm run doc
```
The http://localhost:3000/ back error:
```
Error: No default engine was specified and no extension was provided.
    at new View (E:\Project\Node.Js\novel-api\node_modules\express\lib\view.js:61:11)
    at Function.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\application.js:570:12)
    at ServerResponse.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\response.js:1008:7)
    at E:\Project\Node.Js\novel-api\app.js:79:9
    at Layer.handle_error (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:315:13)
    at E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:275:10)
    at E:\Project\Node.Js\novel-api\app.js:68:5
```
the console return:
```
Error: No default engine was specified and no extension was provided.
    at new View (E:\Project\Node.Js\novel-api\node_modules\express\lib\view.js:61:11)
    at Function.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\application.js:570:12)
    at ServerResponse.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\response.js:1008:7)
    at E:\Project\Node.Js\novel-api\app.js:79:9
    at Layer.handle_error (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:315:13)
    at E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:275:10)
    at E:\Project\Node.Js\novel-api\app.js:68:5
Error: No default engine was specified and no extension was provided.
    at new View (E:\Project\Node.Js\novel-api\node_modules\express\lib\view.js:61:11)
    at Function.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\application.js:570:12)
    at ServerResponse.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\response.js:1008:7)
    at E:\Project\Node.Js\novel-api\app.js:79:9
    at Layer.handle_error (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:315:13)
    at E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:335:12)
    at next (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:275:10)
    at E:\Project\Node.Js\novel-api\app.js:68:5
```

**Comment by lanpangzhi** [comment]
没错呀，这个只是提供了一个接口服务

**Comment by lanpangzhi** [comment]
自己去加静态资源服务器，我用的nginx做的静态资源服务

**Comment by ch4rc0al1080** [comment]
> when i execute:
> 
> ```
> npm run doc
> ```
> 
> The http://localhost:3000/ back error:
> 
> ```
> Error: No default engine was specified and no extension was provided.
>     at new View (E:\Project\Node.Js\novel-api\node_modules\express\lib\view.js:61:11)
>     at Function.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\application.js:570:12)
>     at ServerResponse.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\response.js:1008:7)
>     at E:\Project\Node.Js\novel-api\app.js:79:9
>     at Layer.handle_error (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\layer.js:71:5)
>     at trim_prefix (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:315:13)
>     at E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:284:7
>     at Function.process_params (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:335:12)
>     at next (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:275:10)
>     at E:\Project\Node.Js\novel-api\app.js:68:5
> ```
> 
> the console return:
> 
> ```
> Error: No default engine was specified and no extension was provided.
>     at new View (E:\Project\Node.Js\novel-api\node_modules\express\lib\view.js:61:11)
>     at Function.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\application.js:570:12)
>     at ServerResponse.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\response.js:1008:7)
>     at E:\Project\Node.Js\novel-api\app.js:79:9
>     at Layer.handle_error (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\layer.js:71:5)
>     at trim_prefix (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:315:13)
>     at E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:284:7
>     at Function.process_params (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:335:12)
>     at next (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:275:10)
>     at E:\Project\Node.Js\novel-api\app.js:68:5
> Error: No default engine was specified and no extension was provided.
>     at new View (E:\Project\Node.Js\novel-api\node_modules\express\lib\view.js:61:11)
>     at Function.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\application.js:570:12)
>     at ServerResponse.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\response.js:1008:7)
>     at E:\Project\Node.Js\novel-api\app.js:79:9
>     at Layer.handle_error (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\layer.js:71:5)
>     at trim_prefix (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:315:13)
>     at E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:284:7
>     at Function.process_params (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:335:12)
>     at next (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:275:10)
>     at E:\Project\Node.Js\novel-api\app.js:68:5
> ```

直接访问是错误的，应该加`/index` `/search`这种

**Comment by lanpangzhi** [comment]
> > 当我执行：
> > ```
> > npm run doc
> > ```
> > 
> > 
> > 该[HTTP：//本地主机：3000 /](http://localhost:3000/)回错误：
> > ```
> > Error: No default engine was specified and no extension was provided.
> >     at new View (E:\Project\Node.Js\novel-api\node_modules\express\lib\view.js:61:11)
> >     at Function.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\application.js:570:12)
> >     at ServerResponse.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\response.js:1008:7)
> >     at E:\Project\Node.Js\novel-api\app.js:79:9
> >     at Layer.handle_error (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\layer.js:71:5)
> >     at trim_prefix (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:315:13)
> >     at E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:284:7
> >     at Function.process_params (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:335:12)
> >     at next (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:275:10)
> >     at E:\Project\Node.Js\novel-api\app.js:68:5
> > ```
> > 
> > 
> > 控制台返回：
> > ```
> > Error: No default engine was specified and no extension was provided.
> >     at new View (E:\Project\Node.Js\novel-api\node_modules\express\lib\view.js:61:11)
> >     at Function.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\application.js:570:12)
> >     at ServerResponse.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\response.js:1008:7)
> >     at E:\Project\Node.Js\novel-api\app.js:79:9
> >     at Layer.handle_error (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\layer.js:71:5)
> >     at trim_prefix (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:315:13)
> >     at E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:284:7
> >     at Function.process_params (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:335:12)
> >     at next (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:275:10)
> >     at E:\Project\Node.Js\novel-api\app.js:68:5
> > Error: No default engine was specified and no extension was provided.
> >     at new View (E:\Project\Node.Js\novel-api\node_modules\express\lib\view.js:61:11)
> >     at Function.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\application.js:570:12)
> >     at ServerResponse.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\response.js:1008:7)
> >     at E:\Project\Node.Js\novel-api\app.js:79:9
> >     at Layer.handle_error (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\layer.js:71:5)
> >     at trim_prefix (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:315:13)
> >     at E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:284:7
> >     at Function.process_params (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:335:12)
> >     at next (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:275:10)
> >     at E:\Project\Node.Js\novel-api\app.js:68:5
> > ```
> 
> 直接访问是错误的，加应该`/index` `/search`这种

是的，因为这个服务没有做静态资源解析，npm run doc 生成的文档，还需要手动配置nginx解析

**Comment by ch4rc0al1080** [comment]
> > > 当我执行：
> > > ```
> > > npm run doc
> > > ```
> > > 
> > > 
> > > 该[HTTP：//本地主机：3000 /](http://localhost:3000/)回错误：
> > > ```
> > > Error: No default engine was specified and no extension was provided.
> > >     at new View (E:\Project\Node.Js\novel-api\node_modules\express\lib\view.js:61:11)
> > >     at Function.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\application.js:570:12)
> > >     at ServerResponse.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\response.js:1008:7)
> > >     at E:\Project\Node.Js\novel-api\app.js:79:9
> > >     at Layer.handle_error (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\layer.js:71:5)
> > >     at trim_prefix (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:315:13)
> > >     at E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:284:7
> > >     at Function.process_params (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:335:12)
> > >     at next (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:275:10)
> > >     at E:\Project\Node.Js\novel-api\app.js:68:5
> > > ```
> > > 
> > > 
> > > 控制台返回：
> > > ```
> > > Error: No default engine was specified and no extension was provided.
> > >     at new View (E:\Project\Node.Js\novel-api\node_modules\express\lib\view.js:61:11)
> > >     at Function.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\application.js:570:12)
> > >     at ServerResponse.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\response.js:1008:7)
> > >     at E:\Project\Node.Js\novel-api\app.js:79:9
> > >     at Layer.handle_error (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\layer.js:71:5)
> > >     at trim_prefix (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:315:13)
> > >     at E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:284:7
> > >     at Function.process_params (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:335:12)
> > >     at next (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:275:10)
> > >     at E:\Project\Node.Js\novel-api\app.js:68:5
> > > Error: No default engine was specified and no extension was provided.
> > >     at new View (E:\Project\Node.Js\novel-api\node_modules\express\lib\view.js:61:11)
> > >     at Function.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\application.js:570:12)
> > >     at ServerResponse.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\response.js:1008:7)
> > >     at E:\Project\Node.Js\novel-api\app.js:79:9
> > >     at Layer.handle_error (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\layer.js:71:5)
> > >     at trim_prefix (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:315:13)
> > >     at E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:284:7
> > >     at Function.process_params (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:335:12)
> > >     at next (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:275:10)
> > >     at E:\Project\Node.Js\novel-api\app.js:68:5
> > > ```
> > 
> > 
> > 直接访问是错误的，加应该`/index` `/search`这种
> 
> 是的，因为这个服务没有做静态资源解析，npm run doc 生成的文档，还需要手动配置nginx解析

因为这个我怀疑了半天人生，差点重装服务器系统重来一边了>_<
2333

**Comment by lanpangzhi** [comment]
> > > > 当我执行：
> > > > ```
> > > > npm run doc
> > > > ```
> > > > 
> > > > 
> > > > 该[HTTP：//本地主机：3000 /](http://localhost:3000/)回错误：
> > > > ```
> > > > Error: No default engine was specified and no extension was provided.
> > > >     at new View (E:\Project\Node.Js\novel-api\node_modules\express\lib\view.js:61:11)
> > > >     at Function.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\application.js:570:12)
> > > >     at ServerResponse.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\response.js:1008:7)
> > > >     at E:\Project\Node.Js\novel-api\app.js:79:9
> > > >     at Layer.handle_error (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\layer.js:71:5)
> > > >     at trim_prefix (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:315:13)
> > > >     at E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:284:7
> > > >     at Function.process_params (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:335:12)
> > > >     at next (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:275:10)
> > > >     at E:\Project\Node.Js\novel-api\app.js:68:5
> > > > ```
> > > > 
> > > > 
> > > > 控制台返回：
> > > > ```
> > > > Error: No default engine was specified and no extension was provided.
> > > >     at new View (E:\Project\Node.Js\novel-api\node_modules\express\lib\view.js:61:11)
> > > >     at Function.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\application.js:570:12)
> > > >     at ServerResponse.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\response.js:1008:7)
> > > >     at E:\Project\Node.Js\novel-api\app.js:79:9
> > > >     at Layer.handle_error (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\layer.js:71:5)
> > > >     at trim_prefix (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:315:13)
> > > >     at E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:284:7
> > > >     at Function.process_params (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:335:12)
> > > >     at next (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:275:10)
> > > >     at E:\Project\Node.Js\novel-api\app.js:68:5
> > > > Error: No default engine was specified and no extension was provided.
> > > >     at new View (E:\Project\Node.Js\novel-api\node_modules\express\lib\view.js:61:11)
> > > >     at Function.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\application.js:570:12)
> > > >     at ServerResponse.render (E:\Project\Node.Js\novel-api\node_modules\express\lib\response.js:1008:7)
> > > >     at E:\Project\Node.Js\novel-api\app.js:79:9
> > > >     at Layer.handle_error (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\layer.js:71:5)
> > > >     at trim_prefix (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:315:13)
> > > >     at E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:284:7
> > > >     at Function.process_params (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:335:12)
> > > >     at next (E:\Project\Node.Js\novel-api\node_modules\express\lib\router\index.js:275:10)
> > > >     at E:\Project\Node.Js\novel-api\app.js:68:5
> > > > ```
> > > 
> > > 
> > > 直接访问是错误的，加应该`/index` `/search`这种
> > 
> > 
> > 是的，因为这个服务没有做静态资源解析，npm run doc 生成的文档，还需要手动配置nginx解析
> 
> 因为这个我怀疑了半天人生，差点重装服务器系统重来一边了>_<
> 2333

README文件改了，之前是我忘写了
